
let config=loadConfig(),previewConfig=null;let logoClicks=0,logoClickTimer=null;
const $=id=>document.getElementById(id);
function clone(o){return JSON.parse(JSON.stringify(o))}
function loadConfig(){const s=localStorage.getItem("ckdConfig");if(!s)return clone(window.CKD_CONFIG);try{return {...clone(window.CKD_CONFIG),...JSON.parse(s)}}catch{return clone(window.CKD_CONFIG)}}
function saveConfig(){localStorage.setItem("ckdConfig",JSON.stringify(config))}
function status(m){$("status").textContent=m;setTimeout(()=>{$("status").textContent=""},2500)}
function formatIban(i){return i.replace(/\s+/g,"").replace(/(.{4})/g,"$1 ").trim()}
function buildReference(){let v=$("referenceSelect").value==="__custom__"?$("customRef").value:$("referenceSelect").value;v=(v||"Backnang").trim().replace(/^CKD[-\s]*/i,"");return config.referencePrefix+v}
function makePayload(ref,cfg=config){ref=ref||buildReference(); if(!arguments[0]) $("finalReference").textContent=ref; return ["BCD","002","1","SCT",cfg.bic.replace(/\s+/g,""),cfg.beneficiaryName,cfg.iban.replace(/\s+/g,""),"","","",ref,""].join("\n")}
function drawQR(canvas,cfg,ref){new QRious({element:canvas,value:makePayload(ref,cfg),size:canvas.width,level:"H",background:"white",foreground:"black"});const ctx=canvas.getContext("2d"),logo=new Image();logo.onload=()=>{const W=canvas.width,lw=W*(+cfg.logoPercent/100),lh=logo.height*(lw/logo.width),cd=Math.max(lw,lh)*(+cfg.circleMarginPercent/100),cx=W/2,cy=W/2,r=cd/2,bw=+cfg.borderWidth,bo=+cfg.borderOpacity/100,so=+cfg.shadowOpacity/100,sb=+cfg.shadowBlur,sof=+cfg.shadowOffset;ctx.save();if(so>0&&sb>0){ctx.shadowColor=`rgba(0,0,0,${so})`;ctx.shadowBlur=sb;ctx.shadowOffsetY=sof}ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fillStyle="white";ctx.fill();ctx.restore();if(bw>0&&bo>0){ctx.save();ctx.beginPath();ctx.arc(cx,cy,r-bw/2,0,Math.PI*2);ctx.lineWidth=bw;ctx.strokeStyle=`rgba(80,80,80,${bo})`;ctx.stroke();ctx.restore()}ctx.drawImage(logo,cx-lw/2,cy-lh/2,lw,lh)};logo.src="logo.png"}
function generateQR(){drawQR($("qrCanvas"),config)}
function renderPreview(){if(!previewConfig)previewConfig=clone(config);drawQR($("previewCanvas"),previewConfig,previewConfig.referencePrefix+"Backnang")}
function populate(){for(const id of ["referenceSelect","plateCongregationSelect"]){$(id).innerHTML="";config.congregations.forEach(n=>{let o=document.createElement("option");o.value=n;o.textContent=n;$(id).appendChild(o)});let c=document.createElement("option");c.value="__custom__";c.textContent="Outra...";$(id).appendChild(c)}$("displayName").textContent=config.beneficiaryName;$("displayIban").textContent=formatIban(config.iban);$("displayBic").textContent=config.bic}
function plateName(){let n=$("plateCongregationSelect").value;if(n==="__custom__")n=$("plateCustomName").value||"Backnang";return n.trim()||"Backnang"}
async function renderPlateFor(canvas,name,size){if(size==="A4"){canvas.width=2480;canvas.height=3508}else{canvas.width=1748;canvas.height=2480}const ctx=canvas.getContext("2d"),W=canvas.width,H=canvas.height,ref=config.referencePrefix+name.replace(/^CKD[-\s]*/i,"");ctx.fillStyle="#fff";ctx.fillRect(0,0,W,H);ctx.strokeStyle="#d9d9d9";ctx.lineWidth=Math.max(6,W*.006);ctx.strokeRect(W*.055,H*.045,W*.89,H*.91);await new Promise(res=>{const logo=new Image();logo.onload=()=>{const lw=W*.36,lh=logo.height*(lw/logo.width);ctx.drawImage(logo,(W-lw)/2,H*.07,lw,lh);ctx.fillStyle="#111";ctx.textAlign="center";ctx.font=`700 ${Math.round(W*.065)}px Arial`;ctx.fillText(name,W/2,H*.245);ctx.font=`400 ${Math.round(W*.032)}px Arial`;ctx.fillText(config.plateSubtitleDe,W/2,H*.292);ctx.font=`400 ${Math.round(W*.030)}px Arial`;ctx.fillText(config.plateSubtitlePt,W/2,H*.33);const qs=Math.round(W*(+config.plateQrPercent/100)),off=document.createElement("canvas");off.width=qs;off.height=qs;drawQR(off,config,ref);setTimeout(()=>{ctx.drawImage(off,(W-qs)/2,H*.39,qs,qs);ctx.font=`700 ${Math.round(W*.034)}px Arial`;ctx.fillStyle="#111";ctx.fillText(config.plateBlessingDe,W/2,H*.83);ctx.font=`400 ${Math.round(W*.031)}px Arial`;ctx.fillText(config.plateBlessingPt,W/2,H*.865);ctx.fillStyle="#666";ctx.font=`400 ${Math.round(W*.020)}px Arial`;ctx.fillText(config.beneficiaryName,W/2,H*.925);ctx.fillText(formatIban(config.iban)+"  •  "+config.bic,W/2,H*.95);res()},180)};logo.src="logo.png"})}
async function renderPlate(){await renderPlateFor($("plateCanvas"),plateName(),$("plateSize").value)}
async function downloadPlatePng(){await renderPlate();let a=document.createElement("a"),n=plateName().replace(/[^A-Za-z0-9_-]/g,"_"),s=$("plateSize").value;a.download=`CKD_Placa_${s}_${n}.png`;a.href=$("plateCanvas").toDataURL("image/png");a.click()}
async function downloadPlatePdf(){await renderPlate();const{jsPDF}=window.jspdf,s=$("plateSize").value,w=s==="A4"?210:148,h=s==="A4"?297:210,n=plateName().replace(/[^A-Za-z0-9_-]/g,"_"),pdf=new jsPDF({orientation:"portrait",unit:"mm",format:s.toLowerCase()});pdf.addImage($("plateCanvas").toDataURL("image/png"),"PNG",0,0,w,h);pdf.save(`CKD_Placa_${s}_${n}.pdf`)}
async function downloadAllPlatesPdf(){const{jsPDF}=window.jspdf,s=$("plateSize").value,w=s==="A4"?210:148,h=s==="A4"?297:210,pdf=new jsPDF({orientation:"portrait",unit:"mm",format:s.toLowerCase()}),tmp=document.createElement("canvas");for(let i=0;i<config.congregations.length;i++){if(i>0)pdf.addPage(s.toLowerCase(),"portrait");await renderPlateFor(tmp,config.congregations[i],s);pdf.addImage(tmp.toDataURL("image/png"),"PNG",0,0,w,h)}pdf.save(`CKD_Todas_Placas_${s}.pdf`)}
function setPair(id,v){$(id).value=v;$(id+"Range").value=v}
function bindPair(id,key,min,max){const n=$(id),r=$(id+"Range");function u(v){v=Math.max(min,Math.min(max,+v));n.value=v;r.value=v;previewConfig[key]=v;renderPreview()}n.oninput=()=>u(n.value);r.oninput=()=>u(r.value)}
function bindConfigPair(id,key,min,max,cb){const n=$(id),r=$(id+"Range");function u(v){v=Math.max(min,Math.min(max,+v));n.value=v;r.value=v;config[key]=v;if(cb)cb()}n.oninput=()=>u(n.value);r.oninput=()=>u(r.value)}
function fillAdmin(){previewConfig=clone(config);$("adminPassword").value=config.adminPassword;$("adminPrefix").value=config.referencePrefix;$("adminName").value=config.beneficiaryName;$("adminIban").value=config.iban;$("adminBic").value=config.bic;$("adminCongregations").value=config.congregations.join("\n");$("adminPlateSubtitleDe").value=config.plateSubtitleDe;$("adminPlateSubtitlePt").value=config.plateSubtitlePt;$("adminPlateBlessingDe").value=config.plateBlessingDe;$("adminPlateBlessingPt").value=config.plateBlessingPt;setPair("adminPlateQrPercent",config.plateQrPercent);["LogoPercent","CircleMarginPercent","BorderWidth","BorderOpacity","ShadowOpacity","ShadowBlur","ShadowOffset"].forEach(x=>setPair("preview"+x,config[x.charAt(0).toLowerCase()+x.slice(1)]));renderPreview()}
function readFields(t){t.adminPassword=$("adminPassword").value.trim()||"CKD2025";t.referencePrefix=$("adminPrefix").value.trim()||"CKD-";t.beneficiaryName=$("adminName").value.trim();t.iban=$("adminIban").value.replace(/\s+/g,"").trim();t.bic=$("adminBic").value.replace(/\s+/g,"").trim();t.congregations=$("adminCongregations").value.split("\n").map(x=>x.trim()).filter(Boolean);t.plateSubtitleDe=$("adminPlateSubtitleDe").value.trim();t.plateSubtitlePt=$("adminPlateSubtitlePt").value.trim();t.plateBlessingDe=$("adminPlateBlessingDe").value.trim();t.plateBlessingPt=$("adminPlateBlessingPt").value.trim();t.plateQrPercent=+$("adminPlateQrPercent").value}
function init(){populate();$("customRefBox").classList.add("hidden");generateQR();renderPlate()}
$("ckdLogo").onclick=()=>{logoClicks++;clearTimeout(logoClickTimer);logoClickTimer=setTimeout(()=>logoClicks=0,1400);if(logoClicks>=5){logoClicks=0;$("loginModal").classList.remove("hidden");$("passwordInput").focus()}}
$("loginBtn").onclick=()=>{if($("passwordInput").value===config.adminPassword){$("loginModal").classList.add("hidden");$("userPanel").classList.add("hidden");$("adminPanel").classList.remove("hidden");fillAdmin()}else $("loginError").classList.remove("hidden")}
$("cancelLoginBtn").onclick=()=>$("loginModal").classList.add("hidden");$("exitAdminBtn").onclick=()=>{$("adminPanel").classList.add("hidden");$("userPanel").classList.remove("hidden");init()}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".pane").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.main).classList.add("active");if(b.dataset.main==="platePane")renderPlate()})
document.querySelectorAll(".adm").forEach(b=>b.onclick=()=>{document.querySelectorAll(".adm").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".admPane").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active");if(b.dataset.tab==="qrTab")renderPreview()})
$("referenceSelect").onchange=()=>{$("customRefBox").classList.toggle("hidden",$("referenceSelect").value!=="__custom__");generateQR()};$("customRef").oninput=generateQR;$("generateBtn").onclick=generateQR;$("downloadBtn").onclick=()=>{generateQR();setTimeout(()=>{let a=document.createElement("a");a.download=`CKD_SEPA_${buildReference()}.png`;a.href=$("qrCanvas").toDataURL("image/png");a.click()},300)}
$("plateCongregationSelect").onchange=()=>{$("plateCustomBox").classList.toggle("hidden",$("plateCongregationSelect").value!=="__custom__");renderPlate()};$("plateCustomName").oninput=renderPlate;$("plateSize").onchange=renderPlate;$("renderPlateBtn").onclick=renderPlate;$("downloadPlatePngBtn").onclick=downloadPlatePng;$("downloadPlatePdfBtn").onclick=downloadPlatePdf;$("downloadAllPlatesPdfBtn").onclick=downloadAllPlatesPdf;
$("cancelPreviewBtn").onclick=()=>{previewConfig=clone(config);fillAdmin();status("Prévia cancelada")};$("applyPreviewBtn").onclick=()=>{readFields(previewConfig);config=clone(previewConfig);init();status("Aplicado nesta sessão")};$("saveFromPreviewBtn").onclick=$("saveAdminBtn").onclick=()=>{readFields(previewConfig);config=clone(previewConfig);saveConfig();init();fillAdmin();status("Configurações salvas")}
$("resetAdminBtn").onclick=()=>{localStorage.removeItem("ckdConfig");config=clone(window.CKD_CONFIG);init();fillAdmin();status("Restaurado")};$("exportConfigBtn").onclick=()=>{let blob=new Blob(["window.CKD_CONFIG = "+JSON.stringify(config,null,2)+";\n"],{type:"text/javascript"}),a=document.createElement("a");a.download="config.js";a.href=URL.createObjectURL(blob);a.click()}
$("importConfigFile").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let m=String(r.result).match(/window\.CKD_CONFIG\s*=\s*(\{[\s\S]*\})\s*;?/);config={...clone(window.CKD_CONFIG),...Function("return "+m[1])()};saveConfig();init();fillAdmin();status("Importado")}catch{status("Erro ao importar")}};r.readAsText(f)}
bindPair("previewLogoPercent","logoPercent",5,25);bindPair("previewCircleMarginPercent","circleMarginPercent",120,220);bindPair("previewBorderWidth","borderWidth",0,18);bindPair("previewBorderOpacity","borderOpacity",0,100);bindPair("previewShadowOpacity","shadowOpacity",0,100);bindPair("previewShadowBlur","shadowBlur",0,40);bindPair("previewShadowOffset","shadowOffset",0,20);bindConfigPair("adminPlateQrPercent","plateQrPercent",35,65,renderPlate)
document.querySelectorAll(".copy").forEach(btn=>btn.onclick=async()=>{await navigator.clipboard.writeText(btn.dataset.copy==="iban"?config.iban:config.bic);status("Copiado")})
init();
